# AllCops:
#   DisabledByDefault: true
#   Include:
#     - '**/*.rb'
#   Exclude:
#     - 'vendor/**/*'
#     - 'db/**/*'
#     - 'node_modules/**/*'

# Style/FrozenStringLiteralComment:
#   Enabled: false

# Layout/IndentationStyle:
#   EnforcedStyle: spaces
#   IndentationWidth: 2

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - config/**/*
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*
